version: '3.8'
services:
  client:
    #for debug tun client sh
    #entrypoint: ["sh", "-c", "sleep infinity"]
    build:
      context: .
      dockerfile: Dockerfile
    container_name: air_quality_dashboard
    env_file:
      - ./.env
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3380:8080'

