version: '3.0'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: air_quality_dashboard
    env_file:
      - ./.env
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3380:8080'

